import { mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const base = 'https://t-rafi.github.io/my_portfolio/';
const theme = `try{const t=localStorage.getItem('rafi-theme');if(t==='light'||t==='dark')document.documentElement.dataset.theme=t}catch{}`;
const hash = createHash('sha256').update(theme).digest('base64');
function head(title,description,path='',prefix='',noindex=false){return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'sha256-${hash}'; style-src 'self'; img-src 'self'; font-src 'self'; connect-src https://api.emailjs.com; object-src 'none'; base-uri 'self'; form-action 'none'">
<script>${theme}</script>
<title>${title}</title><meta name="description" content="${description}">
<link rel="canonical" href="${base}${path}">${noindex?'<meta name="robots" content="noindex">':''}
<meta name="color-scheme" content="light dark"><meta name="theme-color" content="#0d1117">
<meta property="og:type" content="website"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${base}${path}"><meta property="og:image" content="${base}assets/images/og.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Towhidul Islam Rafi. Business-critical ERP software. ASP.NET Core, SQL Server, RDLC and IIS."><meta name="twitter:card" content="summary_large_image">
<link rel="icon" type="image/svg+xml" href="${prefix}assets/images/favicon.svg">
<link rel="preload" href="${prefix}assets/fonts/jakarta-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="${prefix}assets/fonts/inter-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="${prefix}assets/css/tokens.css"><link rel="stylesheet" href="${prefix}assets/css/site.css">
<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Person',name:'Towhidul Islam Rafi',jobTitle:'Junior Software Engineer',url:base,email:'mailto:tirafi29@gmail.com',image:`${base}assets/images/profile-512.webp`,address:{'@type':'PostalAddress',addressCountry:'BD'},worksFor:{'@type':'Organization',name:'iTech Velocity'},sameAs:['https://github.com/t-rafi','https://linkedin.com/in/t-rafi'],knowsAbout:['ASP.NET Core','EF Core','SQL Server','RDLC reporting','IIS','REST APIs']})}</script>
<script type="module" src="${prefix}assets/js/site.js"></script>
</head><body><a class="skip-link" href="#main">Skip to content</a>`;}
function header(prefix=''){const home=prefix?'../index.html':'';return `<header class="site-header"><div class="container header-inner"><a class="wordmark" href="${home||'#top'}" aria-label="Rafi, home">rafi<span>.</span></a><div class="header-right"><nav class="nav-links" aria-label="Main navigation"><a href="${home}#work">Work</a><a class="nav-experience" href="${home}#experience">Experience</a><a href="${home}#contact">Contact</a></nav><button class="theme-toggle" type="button" data-theme-toggle aria-label="Switch theme" hidden><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="12" cy="12" r="8"/><path d="M12 4a8 8 0 0 0 0 16Z" fill="currentColor" stroke="none"/></svg></button></div></div></header>`;}
function footer(prefix=''){return `<footer class="site-footer"><div class="container footer-inner"><p>© 2026 Towhidul Islam Rafi · Bangladesh</p><p>Built with care. <a href="https://github.com/t-rafi/my_portfolio">View source</a> <span aria-hidden="true">↗</span></p></div></footer></body></html>`;}
function visual(name,alt,prefix='',loading='lazy'){return `<picture><source type="image/avif" srcset="${prefix}assets/images/${name}-600.avif 600w, ${prefix}assets/images/${name}-1200.avif 1200w" sizes="(max-width: 640px) calc(100vw - 40px), (max-width: 900px) calc(100vw - 48px), 600px"><img src="${prefix}assets/images/${name}-600.webp" srcset="${prefix}assets/images/${name}-600.webp 600w, ${prefix}assets/images/${name}-1200.webp 1200w" sizes="(max-width: 640px) calc(100vw - 40px), (max-width: 900px) calc(100vw - 48px), 600px" width="1200" height="800" alt="${alt}" loading="${loading}" decoding="async"></picture>`;}
const facts = arr=>`<dl class="project-facts">${arr.map(([label,text])=>`<dt>${label}</dt><dd>${text}</dd>`).join('')}</dl>`;
const home = head('Towhidul Islam Rafi — Software Engineer, ASP.NET Core & ERP','Junior Software Engineer in Bangladesh working on Clarra ERP at iTech Velocity. 30+ RDLC reports, ASP.NET Core APIs, SQL Server and IIS delivery.') + header() + `
<main id="main"><div id="top"></div><section class="hero container" aria-labelledby="hero-title"><div class="hero-grid"><div class="hero-copy"><p class="eyebrow">Junior Software Engineer · Bangladesh</p><h1 id="hero-title">Towhidul Islam Rafi<span aria-hidden="true">.</span></h1><p class="hero-statement">I ship business-critical ERP software.</p><p class="hero-description">ASP.NET Core APIs, RDLC reports, and production support for Clarra ERP at iTech Velocity.</p><div class="actions"><a class="button button-primary" href="#contact">Contact me <span class="arrow" aria-hidden="true">↗</span></a><a class="button" href="assets/cv/Towhidul-Islam-Rafi-CV.pdf" download>Download CV <span class="arrow" aria-hidden="true">↓</span></a></div></div><figure class="hero-portrait"><div class="portrait-wrap"><picture><source type="image/avif" srcset="assets/images/profile-128.avif 128w, assets/images/profile-256.avif 256w, assets/images/profile-512.avif 512w" sizes="(max-width:640px) 64px, (max-width:900px) 200px, 288px"><img src="assets/images/profile-256.webp" srcset="assets/images/profile-128.webp 128w, assets/images/profile-256.webp 256w, assets/images/profile-512.webp 512w" sizes="(max-width:640px) 64px, (max-width:900px) 200px, 288px" width="256" height="288" alt="Portrait of Towhidul Islam Rafi" fetchpriority="high"></picture></div><figcaption class="portrait-caption"><span>Towhidul Islam Rafi</span><span>Based in Bangladesh</span></figcaption></figure></div><div class="proof-grid" aria-label="Experience at a glance"><div class="proof"><strong>30+</strong><span>RDLC business reports</span></div><div class="proof"><strong>20+</strong><span>Developers on the Clarra team</span></div><div class="proof"><strong>API → IIS</strong><span>Development, deployment &amp; support</span></div></div></section>
<section id="work" class="section container" aria-labelledby="work-title"><div class="section-heading"><div><p class="eyebrow">01 / Selected work</p><h2 id="work-title">Software for real workflows.</h2></div><p class="section-note">Two areas of enterprise work, plus this portfolio. Proprietary work is shown with illustrative visuals.</p></div><div class="project-grid">
<article class="project project-featured" data-reveal><div class="project-visual">${visual('report','A dummy monthly sales report with grouped rows and a total. All figures are fictional.')}</div><div class="project-content"><p class="project-kicker">Clarra ERP · Reporting</p><h3>Business reporting,<br>from data to document.</h3>${facts([['Problem','Business requirements need clear, usable reports.'],['Role','Junior Software Engineer in a 20+ developer team.'],['Approach','RDLC report work within Clarra ERP, informed by client requirement discussions.'],['Result','30+ RDLC reports.']])}<div class="project-footer"><span class="tag">RDLC · Enterprise ERP</span><a class="text-link" href="work/rdlc-reporting.html">Read reporting case study <span aria-hidden="true">↗</span></a></div></div></article>
<article class="project" data-reveal><div class="project-visual">${visual('api','Illustrative flow: HTTP request, ASP.NET Core API, EF Core and SQL Server.')}</div><div class="project-content"><p class="project-kicker">Clarra ERP · Backend &amp; delivery</p><h3>Connecting requirements<br>to working APIs.</h3>${facts([['Problem','ERP requirements need to become working software.'],['Role','API development, deployment and production support.'],['Approach','ASP.NET Core REST APIs with EF Core and SQL Server; deployment on IIS.'],['Result','Contributions across development and production support.']])}<div class="project-footer"><span class="tag">ASP.NET Core · EF Core · SQL Server</span><a class="text-link" href="work/erp-api.html">Read API case study <span aria-hidden="true">↗</span></a></div></div></article>
<article class="project" data-reveal><div class="project-visual">${visual('portfolio','Preview of this portfolio showing the introduction, direct contact and CV links.')}</div><div class="project-content"><p class="project-kicker">Personal project · This portfolio</p><h3>A portfolio with<br>a clear purpose.</h3>${facts([['Problem','Help recruiters understand the work in a short visit.'],['Role','Portfolio owner; rebuilt with AI-assisted implementation.'],['Approach','Static HTML, CSS and JavaScript. Accessible themes, direct CV access and responsive visuals.'],['Result','The site you are viewing, hosted on GitHub Pages.']])}<div class="project-footer"><a class="text-link" href="#top">View live page <span aria-hidden="true">↑</span></a><a class="text-link" href="https://github.com/t-rafi/my_portfolio">Source code <span aria-hidden="true">↗</span></a></div></div></article>
</div></section>
<section id="experience" class="section container ruled split-section" aria-labelledby="experience-title"><div class="section-intro"><p class="eyebrow">02 / Experience</p><h2 id="experience-title">In the code.<br>In production.</h2><p>Building experience across software development, business requirements, and delivery.</p></div><ol class="timeline"><li class="timeline-item"><div class="timeline-top"><h3>iTech Velocity</h3><span class="timeline-date">Dec 2025 — Present</span></div><p class="timeline-role">Junior Software Engineer · Clarra ERP</p><ul><li>Work on Clarra ERP as part of a 20+ developer team.</li><li>Contribute 30+ RDLC reports and REST API work using ASP.NET Core, EF Core, and SQL Server.</li><li>Deploy on IIS, support production, and discuss requirements with clients.</li></ul></li><li class="timeline-item"><div class="timeline-top"><h3>Pinovation Tech Ltd</h3><span class="timeline-date">Jun — Dec 2025</span></div><p class="timeline-role">Web Development Intern</p><p class="timeline-summary">Earlier professional experience in web development.</p></li><li class="timeline-item"><div class="timeline-top"><h3>Presidency University of Bangladesh</h3><span class="timeline-date">2026 — Present</span></div><p class="timeline-summary">B.Sc. in Computer Science &amp; Engineering</p></li></ol></section>
<section id="skills" class="section container ruled split-section" aria-labelledby="skills-title"><div class="section-intro"><p class="eyebrow">03 / How I work</p><h2 id="skills-title">Tools, with a purpose.</h2><p>The technologies I use, and where they fit in the work.</p></div><div class="skills-grid"><article class="skill"><h3>Backend</h3><p><strong>ASP.NET Core · REST APIs</strong></p><p>Build API functionality for enterprise ERP requirements.</p></article><article class="skill"><h3>Data</h3><p><strong>EF Core · SQL Server</strong></p><p>Work with application data through EF Core and SQL Server.</p></article><article class="skill"><h3>Reporting</h3><p><strong>RDLC</strong></p><p>Turn business reporting requirements into RDLC reports.</p></article><article class="skill"><h3>Delivery</h3><p><strong>IIS · Production support</strong></p><p>Deploy applications, support production, and discuss requirements with clients.</p></article></div></section>
<section id="contact" class="section container" aria-labelledby="contact-title"><div class="contact-panel"><div class="contact-intro"><p class="eyebrow">04 / Contact</p><h2 id="contact-title">Let’s talk<br>about the work.</h2><p>For an engineering role, a technical conversation, or a question about my experience, send me a message.</p><a class="contact-email" href="mailto:tirafi29@gmail.com">tirafi29@gmail.com</a><div class="social-links"><a class="text-link" href="https://linkedin.com/in/t-rafi">LinkedIn <span aria-hidden="true">↗</span></a><a class="text-link" href="https://github.com/t-rafi">GitHub <span aria-hidden="true">↗</span></a></div><p class="privacy">No analytics or advertising cookies. The form sends your name, email, and message through EmailJS to my inbox. This website has no visitor database. Your theme preference is saved on this device.</p></div><div><form class="contact-form" data-contact-form hidden aria-label="Send Rafi a message"><p class="form-help">All fields are required. A successful send will show a confirmation below.</p><div class="form-row"><div class="field"><label for="contact-name">Name</label><input id="contact-name" name="name" autocomplete="name" required maxlength="120"></div><div class="field"><label for="contact-email">Email</label><input id="contact-email" name="email" type="email" autocomplete="email" required maxlength="254"></div></div><div class="field"><label for="contact-message">Message</label><textarea id="contact-message" name="message" rows="5" required minlength="10" maxlength="5000"></textarea></div><div class="honeypot" aria-hidden="true"><label for="contact-website">Leave this field empty</label><input id="contact-website" name="website" tabindex="-1" autocomplete="off"></div><button type="submit" class="button button-primary">Send message</button><p class="form-status" role="status" aria-live="polite" aria-atomic="true"></p></form><noscript><p>Use the email link to get in touch. The message form requires JavaScript.</p></noscript></div></div></section></main>`+footer();

function casePage({title,description,file,kicker,heading,lede,focus,image,alt,caption,body,next,nextTitle}) {return head(title,description,`work/${file}`,'../')+header('../')+`<main id="main" class="container"><div class="case-hero"><a class="back-link" href="../index.html#work"><span aria-hidden="true">←</span> Back to selected work</a><p class="eyebrow">${kicker}</p><h1>${heading}</h1><p class="case-lede">${lede}</p><dl class="case-meta"><div><dt>Context</dt><dd>Clarra ERP · iTech Velocity</dd></div><div><dt>Role</dt><dd>Junior Software Engineer</dd></div><div><dt>Focus</dt><dd>${focus}</dd></div></dl></div><figure class="case-figure">${visual(image,alt,'../','eager')}<figcaption>${caption}</figcaption></figure><article class="case-body" aria-label="Case study">${body}</article><nav class="case-next" aria-label="Case study navigation"><a class="text-link" href="../index.html#contact">Discuss this work <span aria-hidden="true">↗</span></a><a class="text-link" href="${next}">Next: ${nextTitle} <span aria-hidden="true">→</span></a></nav></main>`+footer('../');}
const reporting=casePage({title:'RDLC reporting in Clarra ERP — Towhidul Islam Rafi',description:'A sanitized overview of Rafi’s RDLC reporting contributions to Clarra ERP. Includes a fictional report layout and the scope of his role.',file:'rdlc-reporting.html',kicker:'Case study 01 / RDLC reporting',heading:'Business data.<br>Reports people can use.',lede:'My work at iTech Velocity includes 30+ RDLC reports for Clarra ERP. This page shares the scope of that work with a fictional report layout.',focus:'Business reporting · RDLC',image:'report',alt:'Dummy monthly sales report. Office supplies, equipment and services sum to BDT 90,000. Every figure is fictional.',caption:'Illustrative RDLC layout, recreated for this portfolio. All names and figures are fictional. This is not a production screenshot.',body:`<section><h2>Problem</h2><p>ERP reporting connects application data with the information people need to do their work. In Clarra ERP, my reporting work sits alongside client requirement discussions and production support.</p></section><section><h2>My role</h2><p>I am a <strong>Junior Software Engineer at iTech Velocity</strong>, working on Clarra ERP in a team of more than 20 developers. My contribution includes <strong>30+ RDLC reports</strong>.</p></section><section><h2>Approach</h2><p>I work on RDLC reporting and participate in client requirement discussions. The layout above is an illustration of a business report: a clear title and period, a readable table, a total, and a page footer.</p><p>The illustration explains the kind of document involved. It does not represent Clarra’s internal design, data model, or a specific client deliverable.</p></section><section><h2>Result</h2><p><strong>30+ RDLC reports</strong> are part of my work on Clarra ERP. I also contribute to production support and client requirement discussions.</p><p>Performance improvements, usage counts, and business impact are not claimed here without verified evidence.</p></section><aside class="todo"><strong>TODO: add a verified reporting example</strong><p>Supply one report’s specific requirement, your implementation decisions, a difficult issue you solved, and a result you can verify. Replace the illustration with an approved, sanitized screenshot if available.</p></aside>`,next:'erp-api.html',nextTitle:'ERP APIs'});
const api=casePage({title:'ERP APIs and delivery — Towhidul Islam Rafi',description:'Rafi’s scope of work on ASP.NET Core REST APIs, EF Core, SQL Server, IIS deployment and production support for Clarra ERP.',file:'erp-api.html',kicker:'Case study 02 / ERP APIs & delivery',heading:'From a requirement<br>to working software.',lede:'REST API work in ASP.NET Core, data access with EF Core and SQL Server, and deployment and support on IIS. My contributions span this path within Clarra ERP.',focus:'REST APIs · Data · IIS',image:'api',alt:'Illustrative request path: an HTTP request reaches ASP.NET Core, EF Core handles data access, and SQL Server stores application data.',caption:'Illustrative technology flow based on the tools I use. This is not Clarra’s internal architecture and contains no confidential implementation details.',body:`<section><h2>Problem</h2><p>Enterprise software requirements need to become functioning application behavior. That work continues through deployment and production support.</p><p>My scope includes client requirement discussions, REST APIs, and support for Clarra ERP.</p></section><section><h2>My role</h2><p>As a <strong>Junior Software Engineer at iTech Velocity</strong>, I contribute to a proprietary ERP product with a <strong>20+ developer team</strong>.</p><p>My work includes ASP.NET Core REST APIs, EF Core, SQL Server, IIS deployment, and production support.</p></section><section><h2>Approach</h2><p>The diagram shows how these technologies relate at a general level:</p><ol><li><strong>ASP.NET Core</strong> handles REST API functionality.</li><li><strong>EF Core and SQL Server</strong> support application data access.</li><li><strong>IIS</strong> is part of application deployment.</li><li><strong>Production support and client discussions</strong> connect the software work with its use.</li></ol><p>Specific endpoints, modules, authentication flows, and database schemas are omitted because they have not been supplied for publication.</p></section><section><h2>Result</h2><p>My experience includes API development, IIS deployment, and production support for Clarra ERP. No response-time improvement, uptime figure, or individual module ownership is claimed without supporting evidence.</p></section><aside class="todo"><strong>TODO: add one approved module example</strong><p>Supply the business problem, your exact contribution, important technical decisions, testing and deployment steps, and a verified result. A sanitized request/response example would make this case study more specific.</p></aside>`,next:'rdlc-reporting.html',nextTitle:'RDLC reporting'});
const missing=head('Page not found — Towhidul Islam Rafi','This page could not be found. Return to Towhidul Islam Rafi’s portfolio.','404.html','/my_portfolio/',true)+header('../')+`<main id="main" class="container"><div class="not-found"><p class="eyebrow">404 / Page not found</p><h1>A wrong turn.</h1><p>The page may have moved. You can return to my work or get in touch directly.</p><div class="actions"><a class="button button-primary" href="/my_portfolio/">Back to portfolio</a><a class="button" href="mailto:tirafi29@gmail.com">Email Rafi</a></div></div></main>`+footer();
await mkdir('docs/work',{recursive:true});
for(const [name,html] of Object.entries({'index.html':home,'work/rdlc-reporting.html':reporting,'work/erp-api.html':api,'404.html':missing}))await writeFile(`docs/${name}`,html);
await writeFile('docs/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['','work/rdlc-reporting.html','work/erp-api.html'].map(path=>`<url><loc>${base}${path}</loc></url>`).join('')}</urlset>\n`);
await writeFile('docs/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${base}sitemap.xml\n`);
await writeFile('docs/.nojekyll','');
console.log('Four static pages authored.');
